'use client'

import Link from 'next/link'
import { useMemo, useState } from 'react'
import { ArrowRight, BookOpen, BriefcaseBusiness, Check, ChevronDown, CircleHelp, Compass, ExternalLink, Heart, Menu, Search, Sparkles, Target, X, Accessibility, Type, Contrast, RotateCcw } from 'lucide-react'
import { categories, faqs, guides, type Category } from '@/data/content'

const icons = { book: BookOpen, search: Search, target: Target, graduation: Compass, briefcase: BriefcaseBusiness, heart: Heart }

export function Logo({ compact = false }: { compact?: boolean }) {
  return <Link href="/" className="flex items-center gap-3" aria-label="Rumo, página inicial"><span className="logo-mark" aria-hidden="true"><BookOpen size={compact ? 19 : 22} /><span className="logo-arrow">↗</span></span><span className={compact ? 'text-lg font-bold tracking-tight' : 'text-xl font-bold tracking-tight'}>Rumo</span></Link>
}

export function AccessibilityPanel() {
  const [open, setOpen] = useState(false)
  const [large, setLarge] = useState(false)
  const [highContrast, setHighContrast] = useState(false)
  const [reduced, setReduced] = useState(false)
  return <div className="accessibility-wrap"><button className="accessibility-trigger" onClick={() => setOpen(!open)} aria-expanded={open} aria-controls="accessibility-panel"><Accessibility size={17} /> Acessibilidade</button>{open && <div id="accessibility-panel" className="accessibility-panel" role="dialog" aria-label="Opções de acessibilidade"><strong>Personalize sua leitura</strong><button onClick={() => setLarge(!large)} aria-pressed={large}><Type size={17} /> {large ? 'Texto padrão' : 'Aumentar texto'}</button><button onClick={() => setHighContrast(!highContrast)} aria-pressed={highContrast}><Contrast size={17} /> {highContrast ? 'Contraste padrão' : 'Alto contraste'}</button><button onClick={() => setReduced(!reduced)} aria-pressed={reduced}><Sparkles size={17} /> {reduced ? 'Movimento padrão' : 'Reduzir movimento'}</button><button onClick={() => { setLarge(false); setHighContrast(false); setReduced(false) }}><RotateCcw size={15} /> Restaurar padrão</button>{(large || highContrast || reduced) && <style>{`:root { ${large ? 'font-size: 110%;' : ''} ${highContrast ? '--muted: #26315f; --line: #9aa4c8;' : ''} } ${reduced ? '*, *::before, *::after { animation-duration: .01ms !important; transition-duration: .01ms !important; scroll-behavior: auto !important; }' : ''}`}</style>}</div>}</div>
}

export function Header() {
  const [open, setOpen] = useState(false)
  return <header className="site-header"><div className="header-inner"><Logo /><nav className="hidden items-center gap-6 lg:flex" aria-label="Navegação principal"><Link href="/estudar" aria-current="page">Explorar</Link><Link href="/faq">Perguntas frequentes</Link><Link href="/sobre">Sobre a Rumo</Link></nav><div className="ml-auto hidden items-center gap-4 md:flex"><Link href="/busca" className="header-search"><Search size={18} /> Buscar</Link><AccessibilityPanel /><Link href="/estudar" className="button button-light">Começar agora <ArrowRight size={16} /></Link></div><button className="mobile-menu-button md:hidden" onClick={() => setOpen(!open)} aria-expanded={open} aria-controls="mobile-navigation" aria-label={open ? 'Fechar menu' : 'Abrir menu'}>{open ? <X /> : <Menu />}</button></div>{open && <nav id="mobile-navigation" className="mobile-nav md:hidden" aria-label="Menu móvel"><Link href="/estudar" onClick={() => setOpen(false)}>Explorar categorias</Link><Link href="/busca" onClick={() => setOpen(false)}>Buscar um tema</Link><Link href="/faq" onClick={() => setOpen(false)}>Perguntas frequentes</Link><Link href="/sobre" onClick={() => setOpen(false)}>Sobre a Rumo</Link><AccessibilityPanel /></nav>}</header>
}

export function Footer() { return <footer className="footer"><div className="footer-inner"><div><Logo compact /><p className="footer-copy">Aprenda, avance, conquiste.<br />Informação para escolher caminhos com mais clareza.</p></div><div className="footer-links"><div><strong>Explorar</strong><Link href="/estudar">Estudar melhor</Link><Link href="/enem">ENEM</Link><Link href="/carreira">Carreira</Link></div><div><strong>Rumo</strong><Link href="/sobre">Sobre nós</Link><Link href="/faq">FAQ</Link><a href="https://www.gov.br/mec/pt-br" target="_blank" rel="noreferrer">Fontes oficiais <ExternalLink size={12} /></a></div></div></div><p className="footer-disclaimer">A Rumo oferece conteúdo informativo e não substitui orientação pedagógica, profissional ou atendimento especializado.</p><div className="footer-bottom">© 2026 Rumo · Aprenda, avance, conquiste.</div></footer> }

export function CategoryCard({ category }: { category: Category }) { const Icon = icons[category.icon as keyof typeof icons] || Compass; return <Link href={`/${category.slug}`} className={`category-card accent-${category.accent}`}><span className="icon-bubble"><Icon size={23} /></span><span><strong>{category.name}</strong><small>{category.description}</small></span><ArrowRight className="card-arrow" size={20} /></Link> }

export function GuideCard({ guide }: { guide: (typeof guides)[number] }) { const category = categories.find((item) => item.slug === guide.category); return <Link href={`/${guide.category}/${guide.slug}`} className="guide-card"><div className="guide-top"><span className={`pill pill-${category?.accent}`}>{category?.name}</span><span className="read-time">{guide.readTime}</span></div><h3>{guide.title}</h3><p>{guide.summary}</p><span className="text-link">Ler guia <ArrowRight size={15} /></span></Link> }

export function FAQ({ items = faqs }: { items?: typeof faqs }) { const [active, setActive] = useState<number | null>(0); return <div className="faq-list">{items.map((item, index) => { const id = `faq-answer-${index}`; return <div className={`faq-item ${active === index ? 'is-open' : ''}`} key={item.question}><button onClick={() => setActive(active === index ? null : index)} aria-expanded={active === index} aria-controls={id}><span>{item.question}</span><ChevronDown size={21} aria-hidden="true" /></button>{active === index && <p id={id}>{item.answer}</p>}</div> })}</div> }

export function SearchPanel() { const [query, setQuery] = useState(''); const results = useMemo(() => { const term = query.toLowerCase().trim(); if (!term) return guides; return guides.filter((guide) => { const category = categories.find((item) => item.slug === guide.category); return `${guide.title} ${guide.summary} ${guide.tags.join(' ')} ${category?.name}`.toLowerCase().includes(term) }) }, [query]); return <div className="search-panel"><div className="search-input-wrap"><Search size={21} /><input autoFocus value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Ex.: ENEM, foco, faculdade..." aria-label="Buscar guias, categorias e temas" /></div><p className="search-hint">{query ? `${results.length} resultado${results.length === 1 ? '' : 's'} encontrado${results.length === 1 ? '' : 's'}` : 'Encontre um ponto de partida para sua próxima decisão.'}</p><div className="search-results">{results.map((guide) => <GuideCard guide={guide} key={guide.slug} />)}{!results.length && <div className="empty-state"><CircleHelp size={25} /><div><strong>Nenhum resultado encontrado</strong><p>Tente uma palavra mais ampla, como “estudo”, “curso” ou “futuro”.</p></div></div>}</div></div> }

export function HomePage() { return <><Header /><main><section className="hero"><div className="hero-copy"><span className="eyebrow"><Sparkles size={14} /> Orientação para o seu próximo passo</span><h1>Seu caminho começa <em>com uma escolha.</em></h1><p>Informação clara para estudar, planejar o futuro e tomar decisões com mais confiança. Sem pressão. No seu ritmo.</p><div className="hero-actions"><Link href="/estudar" className="button button-primary">Quero encontrar meu caminho <ArrowRight size={17} /></Link><Link href="#categorias" className="button button-quiet">Explorar temas</Link></div><div className="hero-note"><span className="note-check"><Check size={13} /></span> Conteúdo educativo, gratuito e feito para você.</div></div><div className="hero-art" aria-label="Ilustração de um livro com caminho ascendente e seta de crescimento"><div className="art-sun"><Sparkles size={24} /></div><div className="art-cap"><span></span></div><div className="art-path path-one"></div><div className="art-path path-two"></div><div className="art-book"><BookOpen size={70} /></div><div className="art-star">✦</div></div></section><section id="categorias" className="section categories-section"><div className="section-heading"><div><span className="eyebrow eyebrow-dark">Explore a Rumo</span><h2>Um lugar para cada <em>próximo passo.</em></h2></div><p>Escolha o tema que mais combina com o que você está vivendo agora.</p></div><div className="categories-grid">{categories.map((category) => <CategoryCard category={category} key={category.slug} />)}</div></section><section className="section featured-section"><div className="section-heading"><div><span className="eyebrow eyebrow-dark">Para começar</span><h2>Guias que podem ajudar hoje.</h2></div><Link href="/busca" className="text-link">Ver todos <ArrowRight size={15} /></Link></div><div className="guides-grid">{guides.slice(0, 3).map((guide) => <GuideCard guide={guide} key={guide.slug} />)}</div></section><section className="support-section"><div className="support-icon"><Heart size={22} /></div><div><strong>Você não precisa decidir tudo agora.</strong><p>Comece por uma pergunta. A Rumo ajuda você a encontrar o próximo passo possível.</p></div><Link href="/faq" className="button button-outline">Tenho uma dúvida <ArrowRight size={16} /></Link></section></main><Footer /></> }

export function InnerLayout({ children }: { children: React.ReactNode }) { return <><Header /><main>{children}</main><Footer /></> }

export { categories, guides }
